// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { ContentBylineCredit, PortableTextBlock } from "emdash";

export interface MediaPost {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  dek?: string;
  cover_image?: { id: string; src?: string; alt?: string; width?: number; height?: number };
  body?: PortableTextBlock[];
  author_name?: string;
  story_date?: string;
  media_kind?: string;
  featured?: boolean;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

declare module "emdash" {
  interface EmDashCollections {
    media_posts: MediaPost;
  }
}